import { Link } from "wouter";
import { Button } from "@/components/ui/button";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#FAFAF7]">
      <nav className="sticky top-0 z-50 bg-[#FAFAF7]/95 backdrop-blur border-b border-border/40">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/"><span className="text-xl font-serif font-bold">Close Looper</span></Link>
          <Link href="/"><Button variant="ghost" size="sm">← Back to Home</Button></Link>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-16 prose prose-sm">
        <h1 className="text-4xl font-serif font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground text-sm mb-10">Last updated: August 1, 2026</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">1. Information We Collect</h2>
        <p className="text-muted-foreground leading-relaxed">We collect information you provide directly: name, email, phone, company, and profile details. We also collect usage data such as emails sent, opened, and engagement metrics to improve the Service.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">2. Gmail Data</h2>
        <p className="text-muted-foreground leading-relaxed">Close Looper requests Gmail send permission and Gmail read-only access. The send permission is used only to send messages you approve from your connected mailbox. Read-only access is used only to identify replies and delivery failures related to messages Close Looper sent, so it can pause the relevant loop. We store encrypted OAuth tokens and the minimum message metadata needed for this function. We do not sell Gmail data, use it for advertising, or allow humans to read it except as needed to provide support you request.</p>
        <p className="text-muted-foreground leading-relaxed">Our use and transfer of information received from Google APIs adheres to the <a className="underline" href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">Google API Services User Data Policy</a>, including the Limited Use requirements.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">3. Contact Data</h2>
        <p className="text-muted-foreground leading-relaxed">Contact information you enter into Close Looper is stored securely and used solely to generate and send emails on your behalf. We do not sell, share, or use your contacts' data for any purpose other than operating the Service for you.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">4. AI and Email Content</h2>
        <p className="text-muted-foreground leading-relaxed">Email content generated by our AI is processed through third-party AI providers. We do not use your email content to train AI models. Generated emails are stored in our database to provide history and analytics features.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">5. Open Tracking</h2>
        <p className="text-muted-foreground leading-relaxed">Emails sent through Close Looper include an invisible tracking pixel that records when the email is opened. This may record an IP address and user agent, which can be personal data in some jurisdictions. Recipients are given an unsubscribe link in every message. Do not use tracking where you lack a lawful basis or required notice; an account-level tracking preference will be added before broad public release.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">6. Data Security</h2>
        <p className="text-muted-foreground leading-relaxed">We use encryption in transit and encrypt stored Gmail OAuth tokens. OAuth tokens are never exposed in client-side code. No system is perfectly secure, and we will update this notice if our practices materially change.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">7. Data Retention</h2>
        <p className="text-muted-foreground leading-relaxed">We retain your data for as long as your account is active. Upon account deletion, we will delete your personal data within 30 days, except where required by law to retain it longer.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">8. Your Rights</h2>
        <p className="text-muted-foreground leading-relaxed">You have the right to access, correct, or delete your personal data at any time. You can export your contact data from the Contacts page. To delete your account and all associated data, contact us directly.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">9. Contact</h2>
        <p className="text-muted-foreground leading-relaxed">For privacy questions or data requests, contact us at the email address in your account settings.</p>
      </div>
    </div>
  );
}
