import { Link } from "wouter";
import { Button } from "@/components/ui/button";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#FAFAF7]">
      <nav className="sticky top-0 z-50 bg-[#FAFAF7]/95 backdrop-blur border-b border-border/40">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/"><span className="text-xl font-serif font-bold">Close Looper</span></Link>
          <Link href="/"><Button variant="ghost" size="sm">← Back to Home</Button></Link>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-16 prose prose-sm">
        <h1 className="text-4xl font-serif font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground text-sm mb-10">Last updated: August 1, 2026</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">1. Information We Collect</h2>
        <p className="text-muted-foreground leading-relaxed">We collect information you provide directly: name, email, phone, company, and profile details. We also collect usage data such as emails sent, opened, and engagement metrics to improve the Service.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">2. Gmail Data</h2>
        <p className="text-muted-foreground leading-relaxed">Close Looper connects to your Gmail account to send emails on your behalf. We store OAuth tokens necessary to maintain this connection. We do not read your inbox beyond checking for replies to emails we sent. We do not sell or share your Gmail data with third parties.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">3. Contact Data</h2>
        <p className="text-muted-foreground leading-relaxed">Contact information you enter into Close Looper is stored securely and used solely to generate and send emails on your behalf. We do not sell, share, or use your contacts' data for any purpose other than operating the Service for you.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">4. AI and Email Content</h2>
        <p className="text-muted-foreground leading-relaxed">Email content generated by our AI is processed through third-party AI providers. We do not use your email content to train AI models. Generated emails are stored in our database to provide history and analytics features.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">5. Open Tracking</h2>
        <p className="text-muted-foreground leading-relaxed">Emails sent through Close Looper include an invisible tracking pixel that records when the email is opened. Recipients are notified of this in the email footer. You can disable open tracking in your account settings.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">6. Data Security</h2>
        <p className="text-muted-foreground leading-relaxed">We use industry-standard encryption for data in transit and at rest. OAuth tokens are stored securely and never exposed in client-side code. We conduct regular security reviews of our infrastructure.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">7. Data Retention</h2>
        <p className="text-muted-foreground leading-relaxed">We retain your data for as long as your account is active. Upon account deletion, we will delete your personal data within 30 days, except where required by law to retain it longer.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">8. Your Rights</h2>
        <p className="text-muted-foreground leading-relaxed">You have the right to access, correct, or delete your personal data at any time. You can export your contact data from the Contacts page. To delete your account and all associated data, contact us directly.</p>
        <h2 className="text-xl font-semibold mt-8 mb-3">9. Contact</h2>
        <p className="text-muted-foreground leading-relaxed">For privacy questions or data requests, contact us at the email address in your account settings.</p>
      </div>
    </div>
  );
}

